fix: allows the ability to highlight the word using the progress bar
ReadAlongs/Studio-Web pull request #286
Opened 2024-05-09 16:43 UTC by deltork

### PR Goal? 

- Allows the ability to highlight the words in the read-along using the progress bar, even if the audio is not currently playing
- Changes to the web-component tests to use a new state-sensitive custom command for play sequence. 

### Fixes? 
#266  #275 

### Feedback sought? 
Progress bar interaction, play/stop.

### Priority? 
Low

### Tests added? 
Updates all web-components tests.

### How to test? 
Clicking around the progress bar

### Confidence? 
high

### Version change? 

no

2024-05-10 19:42 UTC, joanise requested changes
Tested, it works very well. Some comments, but most importantly a question about the semantics of the `disabled` variable.

2024-05-10 19:42 UTC, joanise commented on packages/web-component/cypress/support/commands.js
> +  cy.get("[data-cy=play-button]").should("be.enabled").click();
Ah, clever, this means -- I assume -- we'll wait until it's enabled before clicking it? That makes sense, so this means sometimes were were "clicking" on it before it was even enabled!

2024-05-10 19:42 UTC, joanise commented on packages/web-component/src/components/read-along-component/read-along.tsx
> +        this.audio_howl_sprites.sound?.duration() > 0
What does `sound?.duration()` return when `sound` is undefined? Will that return value be comparable via `> 0`? I assume the intent is if sound is not defined, you want `> 0` to be false, but I just want to make sure we don't raise an exception trying to evaluate `undefined > 0` instead of just having it be fast.

2024-05-10 19:42 UTC, joanise commented on packages/web-component/src/components/read-along-component/read-along.tsx
> +        this.audio_howl_sprites.sound?.duration() > 0
The logic here does not make sense to me, though: we're saying 

    disabled = loaded < 2 && sprites && duration > 0

isn't this backwards? I.e., shouldn't it be

    enabled = loaded >= 2 && sprites && duration > 0
    disabled = !enabled

or maybe more directly

    disabled = loaded < 2 || !sprites || !duration

and maybe even actually 

```
      disabled={
        this.hasLoaded < 2 ||
        !this.audio_howl_sprites?.sound?.duration()
      }
```

2024-05-10 19:42 UTC, joanise commented on packages/web-component/src/components/read-along-component/read-along.tsx
> +        this.audio_howl_sprites.sound?.duration() > 0
And finally, why is the definition of `disabled` in curly braces? Why not regular round ones?
(That's not your change, it was already like that, but I don't understand it.)

2024-05-10 19:42 UTC, joanise commented on packages/web-component/src/utils/utils.ts
> +      if (seek >= self._spriteLeft[j][0]) {
was this a ms vs s mistake all along?

2024-05-14 13:52 UTC, deltork commented on packages/web-component/src/components/read-along-component/read-along.tsx
> +        this.audio_howl_sprites.sound?.duration() > 0
Created a function to walk through the states required for the successful playing of RA

2024-05-15 20:12 UTC, deltork commented on packages/web-component/cypress/support/commands.js
> +  cy.get("[data-cy=play-button]").should("be.enabled").click();
Yes!

2024-05-15 20:16 UTC, deltork commented on packages/web-component/src/utils/utils.ts
> +      if (seek >= self._spriteLeft[j][0]) {
Good catch. This is a result of proper conflict resolution when rebasing. I readded the conversion to ms in the line (184) above.

2024-05-16 14:18 UTC, deltork reviewed
As discussed I have run the CI (see logs https://github.com/ReadAlongs/Studio-Web/actions/runs/9102062098/job/25055245809) 10 times and it has passed 10 times. This patch is ready.

2024-05-16 14:53 UTC, joanise requested changes
Now just a trivial change, my understanding is we should always test for undefined using `===` rather than `==`, otherwise I think this is ready to merge. The web-component works really nicely with these changes.

2024-05-16 14:53 UTC, joanise commented on packages/web-component/src/components/read-along-component/read-along.tsx
> +    if (this.audio_howl_sprites == undefined) return;
I believe this should use `===`.

2024-05-16 14:53 UTC, joanise commented on packages/web-component/src/components/read-along-component/read-along.tsx
> +    if (this.audio_howl_sprites == undefined) return false;
===

2024-05-16 14:53 UTC, joanise commented on packages/web-component/src/components/read-along-component/read-along.tsx
> +    if (this.audio_howl_sprites.sound == undefined) return false;
===

2024-05-17 13:14 UTC, joanise approved these changes
I made the other changes I requested, this is ready now.
Thanks for fixing this problem, I'll be happy to have stable CI back!
And the interface is nicer to use now, which is great!

2024-05-17 13:16 UTC, merged