Apply a few of the misc updates that were assigned
ReadAlongs/Studio-Web pull request #317
Opened 2024-06-18 20:45 UTC by roedoejet

### PR Goal? 

Add improved filelist names to the web bundle and more information to the tour

### Fixes? 

https://github.com/ReadAlongs/Studio-Web/issues/314
https://github.com/ReadAlongs/Studio-Web/issues/303

### Feedback sought? 

Sanity check

### Priority? 

low

### Tests added? 

none (just changing names of files basically)

### How to test? 

Run the tour, or try downloading the web bundle

### Confidence? 

high - tested on my machine.

### Version change? 

No

2024-06-18 21:02 UTC, joanise requested changes
Wow, that was fast. I assume you'd like me to do the translations. I have a small text change suggestion first, then I'll  put that on my TODO list.

2024-06-18 21:02 UTC, joanise commented on packages/studio-web/src/app/editor/editor.component.html
> +          then selected "Offline HTML" as the output.
add "or use the Offline-HTML file included in the Web Bundle download format" or something like that.

2024-06-26 14:33 UTC, deltork approved these changes
Everything looks good! I am approving pending i18n fix. Thanks for taking care of this

2024-06-27 17:22 UTC, joanise approved these changes
Fixed done, translations added, ready to merge.

2024-06-27 17:25 UTC, merged