feat: display annotated sentences
ReadAlongs/Studio-Web pull request #318
Opened 2024-06-26 16:26 UTC by deltork

### PR Goal? 
display manually annotated read-along

### Fixes? 

### Feedback sought? 
UI and format check

### Priority? 
by July 8th

### Tests added? 
yes

### How to test? 
spin up web-component `npx nx dev web-component` and visit http://localhost:8941/ej-fra/index-annotated.html

See test-data/ej-fra/ej-fra-annotated.read long formating 

### Confidence? 
high

### Version change? 
minor

2024-06-27 17:30 UTC, joanise commented
This PR is marked as a draft PR, yet you asked for review. Is it ready?

2024-06-27 17:55 UTC, joanise requested changes
Generally looks good and works well.

One thing: Aidan suggested "removing" instead of just "hiding" the hidden layers, for better rendering, and I agree it would be worth making this change.

2024-06-27 17:55 UTC, joanise commented on packages/web-component/src/components/read-along-component/read-along.tsx
> +        const delimeter = ",";
Typo: should be `delimiter` with an `i` in the third syllable

2024-06-27 17:55 UTC, joanise commented on packages/web-component/src/i18n/messages.spa.json
> +    "annotations-tooltip": "Annotations"
`"Anotaciones"`

2024-07-08 16:03 UTC, deltork commented
> Generally looks good and works well.
> 
> One thing: Aidan suggested "removing" instead of just "hiding" the hidden layers, for better rendering, and I agree it would be worth making this change.

I have added that now. Thanks for the reminder!

2024-07-10 18:54 UTC, joanise approved these changes
This looks good now.

2024-07-10 21:12 UTC, merged